CC=g++ -g 
LIB=-lsfml-graphics -lsfml-window -lsfml-system

all: Element.o MaterialArch.o MatArchNode.o MaterialArchView.o MatArchNodeView.o MaterialPop.o


%.o: %.cpp
	$(CC) -c $<


Element.o:
MaterialPop.o:
MaterialArch.o:
MatArchNode.o:
MaterialArchView.o:
MatArchNodeView.o:
